apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: media-insights-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-media
  template: 
    metadata:
      labels:
        app: smart-media
    spec:
      containers: 
        - name: smart-media
          image: fabioteichmann/smart-media:latest
          imagePullPolicy: Always
          ports:
            - name: http 
              containerPort: 8000
              protocol: TCP 
