apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: "alb-controller"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: "media-insights"
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/success-codes: 200,202
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
spec:
  ingressClassName: alb
  rules:
  - http: 
      paths:
      # TODO: create separate deployments for upload-svc and results-svc
      - pathType: Prefix
        path: /upload-media
        backend:
          service:
            name: smart-media-svc # upload-svc
            port: 
              number: 8000
      - pathType: Prefix
        path: /results
        backend:
          service:
            name: smart-media-svc # results-svc
            port:
              number: 8000



---
# ALB Controller:
# 
# resources created in AWS:
# - ALB
# - target group per service
#
# traffic modes: (1) instance mode, (2) IP mode
# - (1) needs NodePort at service level
# - (2) IP mode funnels traffic directly into the pods
# controlled through annotation: `alb.ingress.kubernetes.io/target-type`
#