apiVersion: v1 
kind: Service 
metadata:
  name: smart-media-svc
spec:
  type: ClusterIP 
  selector:
    app: smart-media 
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP 
      name: http
