name: (2) Build and Deploy Smart-Media

on:
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: log-in-docker-hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./app/
        push: true
        tags: ${{ vars.DOCKERHUB_USER }}/smart-media:latest

  # package-lambda:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4

  #   - uses: actions/setup-python@v5
  #     with:
  #       python-version: 3.12
    
  #   - name: prepare-packages
  #     run: |
  #       bash scripts/lambda_ingest/build_lambda.sh

  #   - uses: actions/upload-artifact@v4 
  #     with:
  #       name: lambda-ingest
  #       path: ./scripts/lambda_ingest/lambda_ingest.zip

  apply-infra:
    # needs: [ package-lambda ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    
    - name: prepare-packages
      run: |
        bash scripts/lambda_ingest/build_lambda.sh

    - name: setup-terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    # - uses: actions/download-artifact@v4 
    #   with:
    #     name: lambda-ingest
    #     path: ./scripts/lambda_ingest/lambda_ingest.zip

    - name: authenticate-to-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: acquire-be-config
      run: |
        aws s3 cp s3://${{ vars.AWS_STATIC_BUCKET }}/terraform/backend/backend.config ./terraform/environments/dev/backend.config

    - name: init-and-validate
      working-directory: terraform/environments/dev/
      run: |
        terraform init -backend-config=backend.config
        terraform validate

    - name: apply
      working-directory: terraform/environments/dev/
      run: |
        terraform apply -auto-approve \
          -var="plat_name=smart-media" \
          -var="env=dev" \
          -var="eks_svc_acc_name=smart-media-cluster-svc-acc" \
          -var="user_ip=${{ vars.USER_IP_ADDRESS }}" \
          -var="s3_static_bucket=${{ vars.AWS_STATIC_BUCKET }}"
        terraform output -json > tf-outputs.json

        echo '### TerraForm Outputs:' >> $GITHUB_STEP_SUMMARY
        terraform output -json >> $GITHUB_STEP_SUMMARY

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: tf-outputs
        path: ./terraform/environments/dev/tf-outputs.json

  deploy-app:
    runs-on: ubuntu-latest
    needs: [ build-app, apply-infra ]
    steps:
    - uses: actions/checkout@v4

    - name: download-artifact
      uses: actions/download-artifact@v4
      with:
        name: tf-outputs

    - name: authenticate-to-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: extract-params
      id: extract
      run: |
        vpc_id=$(jq -r '.vpc_id.value' tf-outputs.json)
        echo "vpc_id=$vpc_id" >> "$GITHUB_OUTPUT"

        cluster_name=$(jq -r '.cluster_name.value' tf-outputs.json)
        echo "cluster_name=$cluster_name" >> "$GITHUB_OUTPUT"

        aws_account_id=$(aws sts get-caller-identity --query Account --output text)
        echo "aws_account_id=$aws_account_id" >> "$GITHUB_OUTPUT"

        svc_acc_annot=$(jq -r '.eks_irsa_role_arn.value' tf-outputs.json)
        echo "svc_acc_annot=$svc_acc_annot" >> "$GITHUB_OUTPUT"

        bastion_id=$(jq -r '.bastion_id.value' tf-outputs.json)
        echo "bastion_id=$bastion_id" >> "$GITHUB_OUTPUT"

        bastion_role_arn=$(jq -r '.bastion_role_arn.value' tf-outputs.json)
        echo "bastion_role_arn=$bastion_role_arn" >> "$GITHUB_OUTPUT"

        bastion_username=$(jq -r '.bastion_username.value' tf-outputs.json)
        echo "bastion_username=$bastion_username" >> "$GITHUB_OUTPUT"

        svc_acc_name=$(jq -r '.eks_svc_acc_name.value' tf-outputs.json)
        echo "svc_acc_name=$svc_acc_name" >> "$GITHUB_OUTPUT"

        dynamo_table=$(jq -r '.dynamodb_status_table.value' tf-outputs.json)
        echo "dynamo_table=$dynamo_table" >> "$GITHUB_OUTPUT"

        kds_stream_name=$(jq -r '.kinesis_stream_name.value' tf-outputs.json)
        echo "kds_stream_name=$kds_stream_name" >> "$GITHUB_OUTPUT"

        s3_media_bucket=$(jq -r '.s3_media_bucket.value' tf-outputs.json)
        echo "s3_media_bucket=$s3_media_bucket" >> "$GITHUB_OUTPUT"

    # - name: set-up-kubeconfig-for-eks
    #   run: |
    #     aws eks update-kubeconfig \
    #       --region ${{ vars.AWS_REGION }} \
    #       --name ${{ steps.extract.outputs.cluster_name }}

    - name: ensure-ssm-readiness
      run: |
        for i in {1..60}; do
          status=$(aws ssm describe-instance-information \
            --filters "Key=InstanceIds,Values=${{ steps.extract.outputs.bastion_id }}" \
            --query "InstanceInformationList[0].PingStatus" \
            --region ${{ vars.AWS_REGION }} \
            --output text)
          if [[ "$status" == "Online" ]]; then
            echo "SSM agent is online."
            break
          else
            echo "Waiting for SSM agent..."
            sleep 10
          fi
        done

    - name: acquire-kubeconfig
      shell: bash
      continue-on-error: true
      run: |  
        set +e

        # Capture command id
        COMMAND_ID=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids ${{ steps.extract.outputs.bastion_id }} \
          --comment "aqu" \
          --parameters commands=["aws eks update-kubeconfig --name ${{ steps.extract.outputs.cluster_name }} --region ${{ vars.AWS_REGION }}"] \
          --region ${{ vars.AWS_REGION }} \
          --query "Command.CommandId" \
          --output text)

        echo "Command (ID="$COMMAND_ID") submitted to bastion host. Waiting for completion..."

        aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id ${{ steps.extract.outputs.bastion_id }} \
          --region ${{ vars.AWS_REGION }}
        WAIT_STATUS=$?
        echo "Wait status... "$WAIT_STATUS""

        # set -e

        # Wait until command is executed
        if [[ "$WAIT_STATUS" -eq 0 ]]; then
          # Get output 
          echo "✅ Command succeeded. Fetching command output from bastion..."
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ steps.extract.outputs.bastion_id }} \
            --region ${{ vars.AWS_REGION }} \
            --output text \
            --query "StandardOutputContent"

        else
          # Get error(s)
          echo "❌ Command failed. Fetching error output (if any) from bastion..."
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ steps.extract.outputs.bastion_id }} \
            --region ${{ vars.AWS_REGION }} \
            --output text \
            --query "StandardErrorContent"
        fi
    # NOTE: Currently needs to be done manually - looking for a fix later; this has been blocking for too long now
    # - name: patch-aws-auth-in-eks
    #   shell: bash
    #   run: |
    #     set +e

    #     # Capture command id
    #     COMMAND_ID=$(aws ssm send-command \
    #       --document-name "AWS-RunShellScript" \
    #       --instance-ids "${{ steps.extract.outputs.bastion_id }}" \
    #       --comment "patch aws-auth in eks" \
    #       --parameters '{"commands":["aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ steps.extract.outputs.cluster_name }}","eksctl create iamidentitymapping --cluster ${{ steps.extract.outputs.cluster_name }} --region ${{ vars.AWS_REGION }} --arn ${{ steps.extract.outputs.bastion_role_arn }} --group system:masters --username ${{ steps.extract.outputs.bastion_username }}"]}' \
    #       --region "${{ vars.AWS_REGION }}" \
    #       --output text \
    #       --query "Command.CommandId")

    #     echo "Command (ID="$COMMAND_ID") submitted to bastion host. Waiting for completion..."

    #     aws ssm wait command-executed \
    #       --command-id "$COMMAND_ID" \
    #       --instance-id ${{ steps.extract.outputs.bastion_id }} \
    #       --region ${{ vars.AWS_REGION }}
    #     WAIT_STATUS=$?

    #     # Wait until command is executed
    #     if [ "$WAIT_STATUS" -eq 0]; then
    #       # Get output 
    #       echo "✅ Command succeeded. Fetching command output from bastion..."
    #       aws ssm get-command-invocation \
    #         --command-id "$COMMAND_ID" \
    #         --instance-id ${{ steps.extract.outputs.bastion_id }} \
    #         --region ${{ vars.AWS_REGION }} \
    #         --output text \
    #         --query "StandardOutputContent"

    #     else
    #       # Get error(s)
    #       echo "❌ Command failed. Fetching error output (if any) from bastion..."
    #       aws ssm get-command-invocation \
    #         --command-id "$COMMAND_ID" \
    #         --instance-id ${{ steps.extract.outputs.bastion_id }} \
    #         --region ${{ vars.AWS_REGION }} \
    #         --output text \
    #         --query "StandardErrorContent"
    #     fi

    - name: install-alb-controller-through-bastion
      shell: bash
      continue-on-error: true
      run: |  
        set +e

        # Capture command id
        COMMAND_ID=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids ${{ steps.extract.outputs.bastion_id }} \
          --comment "install ALB Controller into helm" \
          --parameters commands=["../local/src/bootstrap/eks-alb-controller.sh"] \
          --region ${{ vars.AWS_REGION }} \
          --query "Command.CommandId" \
          --output text)

        echo "Command (ID="$COMMAND_ID") submitted to bastion host. Waiting for completion..."

        aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id ${{ steps.extract.outputs.bastion_id }} \
          --region ${{ vars.AWS_REGION }}
        WAIT_STATUS=$?

        # set -e

        # Wait until command is executed
        if [[ "$WAIT_STATUS" -eq 0 ]]; then
          # Get output 
          echo "✅ Command succeeded. Fetching command output from bastion..."
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ steps.extract.outputs.bastion_id }} \
            --region ${{ vars.AWS_REGION }} \
            --output text \
            --query "StandardOutputContent"

        else
          # Get error(s)
          echo "❌ Command failed. Fetching error output (if any) from bastion..."
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ steps.extract.outputs.bastion_id }} \
            --region ${{ vars.AWS_REGION }} \
            --output text \
            --query "StandardErrorContent"
        fi

    - name: deploy-helm-chart-bastion
      shell: bash
      continue-on-error: true
      run: |
        set +e

        COMMAND_ID=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids ${{ steps.extract.outputs.bastion_id }} \
          --comment "deploy helm chart on EKS" \
          --parameters '{"commands":["aws eks update-kubeconfig --name ${{ steps.extract.outputs.cluster_name }} --region ${{ vars.AWS_REGION }}", "helm upgrade -i smart-media ./helm-charts/smart-media --set image.repository=${{ vars.DOCKERHUB_USER }}/smart-media --set env.logfireUrl=${{ vars.LOGFIRE_URL }} --set env.logfireProjectName=${{ vars.LOGFIRE_PROJECT_NAME }} --set secrets.logfireApiToken=${{ secrets.LOGFIRE_API_KEY}} --set serviceAccount.name=${{ steps.extract.outputs.svc_acc_name }} --set serviceAccount.annotations.'eks\.amazonaws\.com/role-arn'=${{ steps.extract.outputs.svc_acc_annot }} --set region=${{ vars.AWS_REGION }} --set dynamoTable=${{ steps.outputs.dynamo_table }} --set kdsStreamName=${{ steps.outputs.kds_stream_name }} -—set s3MediaBucket=${{ steps.outputs.s3_media_bucket }}"]}' \
          --region ${{ vars.AWS_REGION }} \
          --query "Command.CommandId" \
          --output text)
        
        echo "Command (ID="$COMMAND_ID") submitted to bastion host. Waiting for completion..."

        aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id ${{ steps.extract.outputs.bastion_id }} \
          --region ${{ vars.AWS_REGION }}
        WAIT_STATUS=$?

        # set -e

        # Wait until command is executed
        if [ "$WAIT_STATUS" -eq 0]; then
          # Get output 
          echo "✅ Command succeeded. Fetching command output from bastion..."
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ steps.extract.outputs.bastion_id }} \
            --region ${{ vars.AWS_REGION }} \
            --output text \
            --query "StandardOutputContent"

        else
          # Get error(s)
          echo "❌ Command failed. Fetching error output (if any) from bastion..."
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ steps.extract.outputs.bastion_id }} \
            --region ${{ vars.AWS_REGION }} \
            --output text \
            --query "StandardErrorContent"
        fi
